
package com.systemlogic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hi", targetNamespace = "http://webservice.com/", className = "com.systemlogic.Hi")
    @ResponseWrapper(localName = "hiResponse", targetNamespace = "http://webservice.com/", className = "com.systemlogic.HiResponse")
    @Action(input = "http://webservice.com/Hello/hiRequest", output = "http://webservice.com/Hello/hiResponse")
    public String hi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sum", targetNamespace = "http://webservice.com/", className = "com.systemlogic.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://webservice.com/", className = "com.systemlogic.SumResponse")
    @Action(input = "http://webservice.com/Hello/sumRequest", output = "http://webservice.com/Hello/sumResponse")
    public int sum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
